services:
  - type: web
    name: ecommerce-crawler
    runtime: python
    buildCommand: pip install -r requirements.txt && ./setup.sh
    startCommand: streamlit run streamlit_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.10
